### PR TITLE
Master Sync

### PR DESCRIPTION
**Pull request by xdmtk**
Keeping branches in sync periodically

### CODE REVIEW

**Review by Vel4ta — APPROVED** [review]
Not to familiar with this part of the setup but it looks fine to me

**Review by ArteenGalstyan — APPROVED** [review]
👍

**Comment by nickmartinez-ts** [comment]
> Not to familiar with this part of the setup but it looks fine to me

@Vel4ta Not sure how familiar you are with the 'agile' flow we're working with here but just in case, this type of pull request is done every so often when changes/features we implement have gone into the `develop` branch (represented at https://dev.oviattassistant.com) and have been confirmed not to break anything. 

Once this is the case, we can merge the `develop` branch into the `master` branch (our 'production' branch) and then those changes will go live at https://oviattassistant.com shortly after.

**Comment by xdmtk** [comment]
> Not to familiar with this part of the setup but it looks fine to me

@Vel4ta Not sure how familiar you are with the 'agile' flow we're working with here but just in case, this type of pull request is done every so often when changes/features we implement have gone into the `develop` branch (represented at https://dev.oviattassistant.com) and have been confirmed not to break anything. 

Once this is the case, we can merge the `develop` branch into the `master` branch (our 'production' branch) and then those changes will go live at https://oviattassistant.com shortly after. 

Lol commented with the wrong account at first sorry

**Pull request merged**
